plugins {
    id 'com.android.application'
}

android {
    namespace 'com.turtlemark.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.turtlemark.app'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.8.2'
}
